name: Event Filters
on:
  push:
    branches:
      - dev
      - 'releases/**'
    paths-ignore:
      - 'docs/**'
jobs:
  test-filter :
    runs-on: ubuntu-latest
    steps:
      - name: Success message
        run: echo "Event filters working! Triggered on ${{ github.ref_name }} branch"

